const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 1599,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'higg quality shirt',
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 1999,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.6,
      numReviews: 10,
      description: 'Best in this price Segment',
    },
    {
      _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 1699,
      countInStock: 12,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'Grey Color Pant',
    },
    {
      _id: '4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 1699,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.6,
      numReviews: 10,
      description: 'Best in this price Segment',
    },
  ],
};
export default data;
